language: php

php:
- 5.6
- 7.1
- 7.2
- 7.3

addons:

cache:
  directories:
  - $HOME/.composer/cache

before_script:
- phpenv config-rm xdebug.ini
- composer self-update
- composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs