name: CI

on:
  push:
    branches:
      - migrate-gh-actions


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2']
    steps:
    - name: Action checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer, php-config, phpunit, phpenv
    - name: Install phpenv
      run: git clone git@github.com:phpenv/phpenv.git ~/.phpenv
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: $HOME/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Composer install
      run: |
        phpenv config-rm xdebug.ini
        composer self-update
        composer install --no-interaction --prefer-dist
#    - name: Run scripts
#      run: |
#        vendor/bin/phpunit
#        vendor/bin/phpcs


